.TH "twikiexporter" "1" "11 Sep 2015" "" ""

.SH NAME
twikiexporter - Trident CLI
.SH SYNOPSIS

\fBtwikiexporter \fR [ \fB\fI<commands>\fB\fR ]

.SH "DESCRIPTION"
.PP
twikiexporter is a Wiki Exporter for Trident allowing FosWiki's to be exported.
.SH "SEE ALSO"
.PP
The Trident Website <URL:https://trident.li>.
.SH "AUTHOR"
.PP
Trident was re-written from scratch by Jeroen Massar based on the original Ops-Trust Portal code by Paul Vixie, Ben April, Chris Morrow and Jeroen Massar.
